add: desp in params
gaoliang/pypushdeer pull request #1
Opened 2022-02-04 14:39 UTC by AndyZhuAZ

2022-02-09 09:10 UTC, gaoliang requested changes
1. type 和 result 不要使用实例变量，线程不安全
2. 不要手动反序列化json text，使用 requests 的[ json()](https://docs.python-requests.org/en/latest/user/quickstart/#json-response-content) 方法
3. 单元测试 mock 接口，不要使用真实服务器

2022-02-09 09:10 UTC, gaoliang commented on src/pypushdeer/pypushdeer.py
> +    result = None
局部变量即可

2022-02-09 09:10 UTC, gaoliang commented on src/pypushdeer/pypushdeer.py
> +                self.result = json.loads(json.loads(r.text)["content"]["result"][0])
r.json() 就能自动反序列化，不用手动处理

2022-02-09 14:33 UTC, AndyZhuAZ commented
修改了，不过result返回到是字符串列表，还是得有一个json.loads()。测试只写了两个，这样没问题的话以后再写吧

2022-02-09 15:01 UTC, gaoliang requested changes

2022-02-09 15:01 UTC, gaoliang commented on src/pypushdeer/pypushdeer.py
> +             pushkey: Optional[str or list] = None, text_type: Optional[str] = None):
`Optional[str or list]`  等价于  `Optional[str]`,  改成 Union(str, list, None) 或者直接去掉对 list 的支持

```
>>> typing.Optional[str]
typing.Optional[str]
>>> typing.Optional[str or list]
typing.Optional[str]
```

2022-02-09 15:01 UTC, gaoliang commented on src/pypushdeer/pypushdeer.py
> +                except IndexError:
能够直接判断出来的异常，就不要捕获了

2022-02-09 15:01 UTC, gaoliang commented on src/pypushdeer/pypushdeer.py
> +            except IndexError:
同上

2022-02-10 05:14 UTC, merged

2022-02-10 11:44 UTC, gaoliang commented
感谢 PR，一次发送消息到多个 pushkey 的功能暂时不合入了，应用场景比较少，而且不好控制异常